#!/bin/bash
# Clear Browser Cache Instructions

echo "============================================"
echo "BROWSER CACHE CLEARING INSTRUCTIONS"
echo "============================================"
echo ""
echo "The localStorage error is from CACHED old file."
echo "We fixed it, but your browser is loading the old version."
echo ""
echo "TO FIX:"
echo ""
echo "1. HARD REFRESH (try this first):"
echo "   - Chrome/Firefox: Ctrl+Shift+R (Windows) or Cmd+Shift+R (Mac)"
echo "   - Or: Ctrl+F5 (Windows)"
echo ""
echo "2. CLEAR CACHE COMPLETELY:"
echo "   - Chrome: Ctrl+Shift+Delete"
echo "   - Select: 'Cached images and files'"
echo "   - Time range: 'All time'"
echo "   - Click 'Clear data'"
echo ""
echo "3. CLOSE AND REOPEN BROWSER"
echo "   - Close ALL browser windows"
echo "   - Reopen browser"
echo "   - Navigate to POS again"
echo ""
echo "4. INCOGNITO MODE (quickest test):"
echo "   - Chrome: Ctrl+Shift+N"
echo "   - Firefox: Ctrl+Shift+P"
echo "   - Navigate to: http://localhost:8080/avenzur/admin/pos"
echo ""
echo "============================================"
echo "AFTER CLEARING CACHE:"
echo "============================================"
echo ""
echo "1. Open: http://localhost:8080/avenzur/admin/pos"
echo "2. Press F12 (open Developer Tools)"
echo "3. Check Console tab - should be NO errors"
echo "4. Click Wasfaty button"
echo "5. Enter: 0554712260 / 190583"
echo "6. Click Fetch"
echo "7. Check Console for debug messages"
echo ""
echo "============================================"
